# Keyring and auth
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = systemctl --user start hyprpolkitagent

# Reload Hyprpm plugins
exec-once = hyprpm reload
# Wallpaper
exec-once = hyprpaper
exec-once = waypaper --restore

# Waybar
exec-once = ashell --config-path ~/.config/ashell/config.toml
# Rotation sensor
exec-once = iio-hyprland

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Cursors
exec-once = hyprctl setcursor $cursorTheme $cursorSize
exec-once = gsettings set org.gnome.desktop.interface cursor-theme '$cursorTheme'
exec-once = gsettings set org.gnome.desktop.interface cursor-size $cursorSize

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy
